[PHP]

;;;;;;;;;;;;;;;
; PHP Globals ;
;;;;;;;;;;;;;;;

short_open_tag = Off
output_buffering = 4096
allow_call_time_pass_reference = Off
variables_order = "GPCS"
request_order = "GP"
register_long_arrays = Off
register_argc_argv = Off
magic_quotes_gpc = Off
enable_dl = Off
allow_url_fopen = On
realpath_cache_size = "800K"
realpath_cache_ttl = "86400"
;include_path = ".:/usr/share/pear:/usr/share/php"

[Date]
date.timezone = "America/Denver"

;;;;;;;;;;;;;;;;;;;;;;
;; PACKAGE SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;

; Xdebug
;xdebug.max_nesting_level = 256
;xdebug.show_exception_trace = 0
;xdebug.collect_params = 0
;xdebug.remote_enable = 1

;;;;;;;;;;;;;;;;;;;;;;;
;; PANTHEON SETTINGS ;;
;;;;;;;;;;;;;;;;;;;;;;;

; Globals
expose_php = on
max_execution_time = 3600
max_input_time = 3600
max_input_vars = 10000
memory_limit = 10G
upload_max_filesize = 10G
post_max_size = 10G
error_reporting = E_ALL & ~E_DEPRECATED
ignore_repeated_errors = on
html_errors = on
display_errors = on
display_startup_errors = on
log_errors = on

; Using this to insert essential Pantheon functionality.
;auto_prepend_file = prepend.php

[Opcache]

;opcache.revalidate_freq=0
;opcache.validate_timestamps=0
;opcache.max_accelerated_files=20000
;opcache.memory_consumption=256
;opcache.interned_strings_buffer=16
;opcache.fast_shutdown=1